// Whisper'ın desteklediği ~99 dil. `whisper` alanı whisper.cpp'ye `-l` parametresi
// olarak geçilen kod; `label` arayüzde gösterilen Türkçe ad.
// Sıralama: en çok kullanılanlar üstte, gerisi alfabetik.
export interface LanguageOption {
  label: string;
  whisper: string;
}

export const LANGUAGES: LanguageOption[] = [
  { label: 'Türkçe', whisper: 'tr' },
  { label: 'İngilizce', whisper: 'en' },
  { label: 'Almanca', whisper: 'de' },
  { label: 'Fransızca', whisper: 'fr' },
  { label: 'İspanyolca', whisper: 'es' },
  { label: 'Rusça', whisper: 'ru' },
  { label: 'Arapça', whisper: 'ar' },
  { label: 'Çince', whisper: 'zh' },
  { label: 'Kantonca', whisper: 'yue' },
  { label: 'Japonca', whisper: 'ja' },
  { label: 'Korece', whisper: 'ko' },
  { label: 'Portekizce', whisper: 'pt' },
  { label: 'İtalyanca', whisper: 'it' },
  { label: 'Hollandaca', whisper: 'nl' },
  { label: 'Lehçe', whisper: 'pl' },
  { label: 'Ukraynaca', whisper: 'uk' },
  { label: 'Hintçe', whisper: 'hi' },
  { label: 'Urduca', whisper: 'ur' },
  { label: 'Farsça', whisper: 'fa' },
  { label: 'İbranice', whisper: 'he' },
  { label: 'Yunanca', whisper: 'el' },
  { label: 'İsveççe', whisper: 'sv' },
  { label: 'Norveççe', whisper: 'no' },
  { label: 'Danca', whisper: 'da' },
  { label: 'Fince', whisper: 'fi' },
  { label: 'Çekçe', whisper: 'cs' },
  { label: 'Slovakça', whisper: 'sk' },
  { label: 'Macarca', whisper: 'hu' },
  { label: 'Rumence', whisper: 'ro' },
  { label: 'Bulgarca', whisper: 'bg' },
  { label: 'Sırpça', whisper: 'sr' },
  { label: 'Hırvatça', whisper: 'hr' },
  { label: 'Boşnakça', whisper: 'bs' },
  { label: 'Slovence', whisper: 'sl' },
  { label: 'Makedonca', whisper: 'mk' },
  { label: 'Arnavutça', whisper: 'sq' },
  { label: 'Litvanca', whisper: 'lt' },
  { label: 'Letonca', whisper: 'lv' },
  { label: 'Estonca', whisper: 'et' },
  { label: 'Belarusça', whisper: 'be' },
  { label: 'Ermenice', whisper: 'hy' },
  { label: 'Gürcüce', whisper: 'ka' },
  { label: 'Azerbaycanca', whisper: 'az' },
  { label: 'Kazakça', whisper: 'kk' },
  { label: 'Özbekçe', whisper: 'uz' },
  { label: 'Türkmence', whisper: 'tk' },
  { label: 'Tacikçe', whisper: 'tg' },
  { label: 'Moğolca', whisper: 'mn' },
  { label: 'Vietnamca', whisper: 'vi' },
  { label: 'Tayca', whisper: 'th' },
  { label: 'Endonezce', whisper: 'id' },
  { label: 'Malayca', whisper: 'ms' },
  { label: 'Tagalogca (Filipince)', whisper: 'tl' },
  { label: 'Malgaşça', whisper: 'mg' },
  { label: 'Svahili', whisper: 'sw' },
  { label: 'Hausa Dili', whisper: 'ha' },
  { label: 'Yoruba Dili', whisper: 'yo' },
  { label: 'Şona Dili', whisper: 'sn' },
  { label: 'Somalice', whisper: 'so' },
  { label: 'Afrikaanca', whisper: 'af' },
  { label: 'Amharca', whisper: 'am' },
  { label: 'Bengalce', whisper: 'bn' },
  { label: 'Pencapça', whisper: 'pa' },
  { label: 'Guceratça', whisper: 'gu' },
  { label: 'Marathi Dili', whisper: 'mr' },
  { label: 'Nepalce', whisper: 'ne' },
  { label: 'Sinhala Dili', whisper: 'si' },
  { label: 'Tamilce', whisper: 'ta' },
  { label: 'Teluguca', whisper: 'te' },
  { label: 'Kannada Dili', whisper: 'kn' },
  { label: 'Malayalamca', whisper: 'ml' },
  { label: 'Assamca', whisper: 'as' },
  { label: 'Sindçe', whisper: 'sd' },
  { label: 'Peştuca', whisper: 'ps' },
  { label: 'Kmerce', whisper: 'km' },
  { label: 'Laoca', whisper: 'lo' },
  { label: 'Birmanca', whisper: 'my' },
  { label: 'Tibetçe', whisper: 'bo' },
  { label: 'Nynorsk (Norveççe)', whisper: 'nn' },
  { label: 'İzlandaca', whisper: 'is' },
  { label: 'Faroece', whisper: 'fo' },
  { label: 'Galce', whisper: 'cy' },
  { label: 'İrlandaca', whisper: 'ga' },
  { label: 'Baskça', whisper: 'eu' },
  { label: 'Katalanca', whisper: 'ca' },
  { label: 'Galiçyaca', whisper: 'gl' },
  { label: 'Maltaca', whisper: 'mt' },
  { label: 'Lüksemburgca', whisper: 'lb' },
  { label: 'Oksitanca', whisper: 'oc' },
  { label: 'Bretonca', whisper: 'br' },
  { label: 'Latince', whisper: 'la' },
  { label: 'Sanskritçe', whisper: 'sa' },
  { label: 'Yidiş', whisper: 'yi' },
  { label: 'Haiti Kreyolu', whisper: 'ht' },
  { label: 'Maori Dili', whisper: 'mi' },
  { label: 'Hawaii Dili', whisper: 'haw' },
  { label: 'Lingala', whisper: 'ln' },
  { label: 'Başkurtça', whisper: 'ba' },
  { label: 'Tatarca', whisper: 'tt' },
  { label: 'Cava Dili', whisper: 'jw' },
  { label: 'Sundaca', whisper: 'su' },
];

/** Bir dilin Whisper kodunu bulur, bulunamazsa 'auto' (otomatik algılama) döner. */
export function whisperCodeFor(label: string): string {
  return LANGUAGES.find((l) => l.label === label)?.whisper ?? 'auto';
}
